// user types ////////////////////////////////=>
export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_USER_INFO = "GET_USER_INFO";

// AUTHENTICATION TYPES
export const CHECK_IF_USER_EXISTS = 'CHECK_IF_USER_EXISTS'
export const CHECK_IF_USER_EXISTS_SUCCESS = 'CHECK_IF_USER_EXISTS_SUCCESS'
export const REGISTERING_USER_START = 'REGISTERING_USER_START'
export const REGISTERING_USER_SUCCESS = 'REGISTERING_USER_SUCCESS'
export const SIGNIN_USER_START = 'SIGNIN_USER_START'
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS'
export const SIGNIN_USER_SUCCESS__FAILD = 'SIGNIN_USER_SUCCESS__FAILD'


// FORGOT PASSWORD
export const FORGOT_PASSWORD_SEARCH_START = 'FORGOT_PASSWORD_SEARCH_START'
export const FORGOT_PASSWORD_SEARCH_SUCCESS = 'SIGNIN_USER_SUCCESS'

// VERIFICATION CODE 
export const SEND_VERIFICATION_CODE_START = 'SEND_VERIFICATION_CODE_START'
export const SEND_VERIFICATION_CODE_SUCCESS = 'SEND_VERIFICATION_CODE_SUCCESS'


// RESET USER PASSWORD
export const RESET_PASSWORD_START = 'RESET_PASSWORD_START'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
